/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Classe.CategoriaFerragens;
import Classe.Cliente;
import Classe.Ferragens;
import Classe.Projeto;
import Classe.projeto_ferragen;
import DAO.CategoriaFerragenDAO;
import DAO.ClienteDAO;
import DAO.FerragensDAO;
import DAO.ProjetoDAO;
import DAO.ProjetoFerragemDAO;
import TableModel.CategoriaFerragensTableModel;
import TableModel.ClienteTabelModel;
import TableModel.FerragensTableModel;
import TableModel.ProjetoFerragemTableModel;
import TableModel.ProjetoTableModel;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Usuario
 */
public class Home extends javax.swing.JFrame {

    private static Cliente cliente = new Cliente();
    private static Ferragens ferragens = new Ferragens();
    private static CategoriaFerragens categoriaFerragens = new CategoriaFerragens();
    private static Projeto projeto = new Projeto();
    private boolean iniciar = false;
    
    public Home() {
        initComponents();
        AutoCompleteDecorator.decorate(jCB_ItensFerragens);
        activarJIF(jIF_Home);
        atualizarTabelaBuscarCliente();
        atualizarTabelaBuscarCategoriaFerragen();
        atualizarTabelaBuscarFerragen();
        atualizarTabelaBuscarProjeto();
        
        
        atualizarJcItensCadastrados(jCB_ItensFerragens);
        atualizarJcItensCadastrados(jCB_ProjetoCategoria);
        atualizarJcProjetoCliente();
        
       jCB_ProjetoCategoria.setSelectedIndex(-1);
       
       iniciar = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPlanoFundo = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jIF_Home = new javax.swing.JInternalFrame();
        jPanel14 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jIF_BuscarFerragens = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_BuscarFerragens = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jIf_BuscarCliente = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jTF_BuscarCliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_BuscarCliente = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jIF_BuscarProjeto = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_BuscarProjeto = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jIF_CadastroCliente = new javax.swing.JInternalFrame();
        jPanel7 = new javax.swing.JPanel();
        jTF_NomeCliente = new javax.swing.JTextField();
        jTF_TelefoneCliente = new javax.swing.JTextField();
        jTF_CpfCliente = new javax.swing.JTextField();
        jTF_EnderecoCliente = new javax.swing.JTextField();
        jTF_BairroCliente = new javax.swing.JTextField();
        jTF_CidadeCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jL_CadastrarCliente = new javax.swing.JLabel();
        jCB_ManterTela = new javax.swing.JCheckBox();
        jL_MsgCadastroCliente = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jL_ExcluirCliente = new javax.swing.JLabel();
        jIF_CadastroFerragens = new javax.swing.JInternalFrame();
        jPanel10 = new javax.swing.JPanel();
        jTF_DescricaoFerragen = new javax.swing.JTextField();
        jTF_ValorFerragen = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jL_CadastrarFerragem = new javax.swing.JLabel();
        jCB_ItensFerragens = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCB_ManterTelaCadastroFerragens = new javax.swing.JCheckBox();
        jL_MsgCadastroFerragens = new javax.swing.JLabel();
        jIF_CadastroProjeto = new javax.swing.JInternalFrame();
        jPanel16 = new javax.swing.JPanel();
        jTF_FormaPagamento = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTF_Comodo = new javax.swing.JTextField();
        jTF_NumeroMoveis = new javax.swing.JTextField();
        jCB_ClienteProjeto = new javax.swing.JComboBox<>();
        jDP_DataFinal = new org.jdesktop.swingx.JXDatePicker();
        jDP_DataInicial = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jIF_CadastroProjeto2 = new javax.swing.JInternalFrame();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTb_ProjetoFerragen = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jCB_ProjetoFerragen = new javax.swing.JComboBox<>();
        jCB_ProjetoCategoria = new javax.swing.JComboBox<>();
        jTF_Quantidade = new javax.swing.JTextField();
        jCB_idFerragen = new javax.swing.JComboBox<>();
        jIF_CadastroCategoriaFerragens = new javax.swing.JInternalFrame();
        jPanel19 = new javax.swing.JPanel();
        jTF_DescricaoCategoriaFerragem = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jL_CadastrarCategoriaFerragens = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jL_ExcluirCategoriaFerragem = new javax.swing.JLabel();
        jL_MsgCategoriaFerragem = new javax.swing.JLabel();
        jCB_ManterTelaCategoriaFerragen = new javax.swing.JCheckBox();
        jIF_BuscaCategoriaFerragem = new javax.swing.JInternalFrame();
        jPanel27 = new javax.swing.JPanel();
        jTF_BuscarCategoriaFerragen = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jT_BucarCategoriaFerragem = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelPlanoFundo.setBackground(new java.awt.Color(255, 255, 255));
        JPanelPlanoFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(102, 176, 175));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(191, 154, 83));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Projetos");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 170, 50));

        jPanel3.setBackground(new java.awt.Color(191, 154, 83));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Clientes");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMenu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 50));

        jPanel4.setBackground(new java.awt.Color(191, 154, 83));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ferragens");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 170, -1));

        JPanelPlanoFundo.add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 410));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jIF_Home.setVisible(true);
        jIF_Home.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(191, 154, 83));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jIF_Home.getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 420));

        jDesktopPane1.add(jIF_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 550, 460));

        jIF_BuscarFerragens.setVisible(true);
        jIF_BuscarFerragens.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("Buscar");
        jTextField1.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 326, -1));

        jT_BuscarFerragens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jT_BuscarFerragens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_BuscarFerragensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_BuscarFerragens);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 520, 330));

        jButton1.setText("Adcionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 80, -1));

        jButton2.setText("Buscar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jIF_BuscarFerragens.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 420));

        jDesktopPane1.add(jIF_BuscarFerragens, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 550, 460));

        jIf_BuscarCliente.setVisible(true);
        jIf_BuscarCliente.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jIf_BuscarClienteInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jIf_BuscarCliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTF_BuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_BuscarCliente.setText("Buscar");
        jTF_BuscarCliente.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_BuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_BuscarClienteKeyPressed(evt);
            }
        });
        jPanel5.add(jTF_BuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 326, -1));

        jT_BuscarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome do Cliente", "Telefone", "Cpf"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jT_BuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_BuscarClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jT_BuscarCliente);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 520, 330));

        jButton9.setText("Adcionar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 80, -1));

        jButton10.setText("Buscar");
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jIf_BuscarCliente.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 420));

        jDesktopPane1.add(jIf_BuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 550, 460));

        jIF_BuscarProjeto.setVisible(true);
        jIF_BuscarProjeto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setText("Buscar");
        jTextField3.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jPanel6.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 326, -1));

        jT_BuscarProjeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome do Cliente", "Numero de Moveis", "Valor do Projeto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jT_BuscarProjeto);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 520, 330));

        jButton3.setText("Adcionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 80, -1));

        jButton4.setText("Buscar");
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jIF_BuscarProjeto.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 420));

        jDesktopPane1.add(jIF_BuscarProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 550, 460));

        jIF_CadastroCliente.setVisible(true);
        jIF_CadastroCliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTF_NomeCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_NomeCliente.setText("Nome Completo");
        jTF_NomeCliente.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_NomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_NomeClienteActionPerformed(evt);
            }
        });
        jPanel7.add(jTF_NomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 326, 20));

        jTF_TelefoneCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_TelefoneCliente.setText("Telefone");
        jTF_TelefoneCliente.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_TelefoneCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TelefoneClienteActionPerformed(evt);
            }
        });
        jPanel7.add(jTF_TelefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 326, 20));

        jTF_CpfCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_CpfCliente.setText("Cpf");
        jTF_CpfCliente.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_CpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_CpfClienteActionPerformed(evt);
            }
        });
        jPanel7.add(jTF_CpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 326, 20));

        jTF_EnderecoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_EnderecoCliente.setText("Endereço");
        jTF_EnderecoCliente.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_EnderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_EnderecoClienteActionPerformed(evt);
            }
        });
        jPanel7.add(jTF_EnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 326, 20));

        jTF_BairroCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_BairroCliente.setText("Bairro");
        jTF_BairroCliente.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_BairroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_BairroClienteActionPerformed(evt);
            }
        });
        jPanel7.add(jTF_BairroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 160, 20));

        jTF_CidadeCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_CidadeCliente.setText("Cidade");
        jTF_CidadeCliente.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_CidadeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_CidadeClienteActionPerformed(evt);
            }
        });
        jPanel7.add(jTF_CidadeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 160, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Cadastro de Clientes");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Voltar");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Limpar");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 100, 40));

        jL_CadastrarCliente.setBackground(new java.awt.Color(255, 255, 255));
        jL_CadastrarCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_CadastrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_CadastrarCliente.setText("Cadastrar");
        jL_CadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_CadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_CadastrarClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_CadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_CadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 100, 40));

        jCB_ManterTela.setText("Manter na Tela");
        jPanel7.add(jCB_ManterTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));
        jPanel7.add(jL_MsgCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 250, 20));

        jL_ExcluirCliente.setBackground(new java.awt.Color(255, 255, 255));
        jL_ExcluirCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_ExcluirCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_ExcluirCliente.setText("Excluir");
        jL_ExcluirCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_ExcluirCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_ExcluirClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_ExcluirCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_ExcluirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 100, -1));

        jIF_CadastroCliente.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 420));

        jDesktopPane1.add(jIF_CadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 550, 460));

        jIF_CadastroFerragens.setVisible(true);
        jIF_CadastroFerragens.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTF_DescricaoFerragen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_DescricaoFerragen.setText("Descrição");
        jTF_DescricaoFerragen.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_DescricaoFerragen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_DescricaoFerragenActionPerformed(evt);
            }
        });
        jPanel10.add(jTF_DescricaoFerragen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 326, 20));

        jTF_ValorFerragen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_ValorFerragen.setText("Valor Compra");
        jTF_ValorFerragen.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_ValorFerragen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_ValorFerragenActionPerformed(evt);
            }
        });
        jPanel10.add(jTF_ValorFerragen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 326, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Cadastro de Ferragens");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Voltar");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Limpar");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 100, 40));

        jL_CadastrarFerragem.setBackground(new java.awt.Color(255, 255, 255));
        jL_CadastrarFerragem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_CadastrarFerragem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_CadastrarFerragem.setText("Cadastrar");
        jL_CadastrarFerragem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_CadastrarFerragem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_CadastrarFerragemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_CadastrarFerragem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_CadastrarFerragem, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 100, 40));

        jCB_ItensFerragens.setEditable(true);
        jCB_ItensFerragens.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jPanel10.add(jCB_ItensFerragens, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 280, -1));

        jButton11.setText("+");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 40, -1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Excluir");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Categoria:");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jCB_ManterTelaCadastroFerragens.setText("Manter na Tela");
        jPanel10.add(jCB_ManterTelaCadastroFerragens, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
        jPanel10.add(jL_MsgCadastroFerragens, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 250, 20));

        jIF_CadastroFerragens.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 420));

        jDesktopPane1.add(jIF_CadastroFerragens, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 550, 460));

        jIF_CadastroProjeto.setVisible(true);
        jIF_CadastroProjeto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTF_FormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_FormaPagamento.setText("Forma de Pagamento");
        jTF_FormaPagamento.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_FormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_FormaPagamentoActionPerformed(evt);
            }
        });
        jPanel16.add(jTF_FormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 326, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Cadastro de Projetos");
        jPanel16.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Voltar");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel16.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Limpar");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 100, 40));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Cadastrar");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 100, 40));

        jTF_Comodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_Comodo.setText("Comodo");
        jTF_Comodo.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_Comodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_ComodoActionPerformed(evt);
            }
        });
        jPanel16.add(jTF_Comodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 160, 20));

        jTF_NumeroMoveis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_NumeroMoveis.setText("Numero de Moveis");
        jTF_NumeroMoveis.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_NumeroMoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_NumeroMoveisActionPerformed(evt);
            }
        });
        jPanel16.add(jTF_NumeroMoveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 160, 20));

        jCB_ClienteProjeto.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jPanel16.add(jCB_ClienteProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 330, -1));
        jPanel16.add(jDP_DataFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 250, -1));
        jPanel16.add(jDP_DataInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 250, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data Inicial");
        jPanel16.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data Final");
        jPanel16.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jIF_CadastroProjeto.getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 420));

        jDesktopPane1.add(jIF_CadastroProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 550, 460));

        jIF_CadastroProjeto2.setVisible(true);
        jIF_CadastroProjeto2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTb_ProjetoFerragen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Descrição", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTb_ProjetoFerragen);

        jPanel13.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 520, 330));

        jButton7.setText("Finalizar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 80, -1));

        jButton8.setText("Adcionar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField15.setText("Quantidade");
        jTextField15.setBorder(null);
        jPanel13.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 80, -1));

        jCB_ProjetoFerragen.setEditable(true);
        jCB_ProjetoFerragen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_ProjetoFerragenActionPerformed(evt);
            }
        });
        jPanel13.add(jCB_ProjetoFerragen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 110, -1));

        jCB_ProjetoCategoria.setEditable(true);
        jCB_ProjetoCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCB_ProjetoCategoriaMouseClicked(evt);
            }
        });
        jCB_ProjetoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_ProjetoCategoriaActionPerformed(evt);
            }
        });
        jPanel13.add(jCB_ProjetoCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, -1));
        jPanel13.add(jTF_Quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, -1));

        jPanel13.add(jCB_idFerragen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jIF_CadastroProjeto2.getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 420));

        jDesktopPane1.add(jIF_CadastroProjeto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 550, 460));

        jIF_CadastroCategoriaFerragens.setVisible(true);
        jIF_CadastroCategoriaFerragens.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTF_DescricaoCategoriaFerragem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_DescricaoCategoriaFerragem.setText("Descrição");
        jTF_DescricaoCategoriaFerragem.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jTF_DescricaoCategoriaFerragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_DescricaoCategoriaFerragemActionPerformed(evt);
            }
        });
        jPanel19.add(jTF_DescricaoCategoriaFerragem, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 326, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Cadastro de Categora Ferragens");
        jPanel19.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Voltar");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel19.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Limpar");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 110, 40));

        jL_CadastrarCategoriaFerragens.setBackground(new java.awt.Color(255, 255, 255));
        jL_CadastrarCategoriaFerragens.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_CadastrarCategoriaFerragens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_CadastrarCategoriaFerragens.setText("Cadastrar");
        jL_CadastrarCategoriaFerragens.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_CadastrarCategoriaFerragens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_CadastrarCategoriaFerragensMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_CadastrarCategoriaFerragens, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_CadastrarCategoriaFerragens, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel19.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 100, 40));

        jL_ExcluirCategoriaFerragem.setBackground(new java.awt.Color(255, 255, 255));
        jL_ExcluirCategoriaFerragem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_ExcluirCategoriaFerragem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_ExcluirCategoriaFerragem.setText("Excluir");
        jL_ExcluirCategoriaFerragem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_ExcluirCategoriaFerragem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_ExcluirCategoriaFerragemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(jL_ExcluirCategoriaFerragem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_ExcluirCategoriaFerragem, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel19.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 100, -1));
        jPanel19.add(jL_MsgCategoriaFerragem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 250, 20));

        jCB_ManterTelaCategoriaFerragen.setText("Manter na Tela");
        jPanel19.add(jCB_ManterTelaCategoriaFerragen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jIF_CadastroCategoriaFerragens.getContentPane().add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 420));

        jDesktopPane1.add(jIF_CadastroCategoriaFerragens, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 550, 460));

        jIF_BuscaCategoriaFerragem.setVisible(true);
        jIF_BuscaCategoriaFerragem.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jIF_BuscaCategoriaFerragemInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jIF_BuscaCategoriaFerragemInternalFrameOpened(evt);
            }
        });
        jIF_BuscaCategoriaFerragem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jIF_BuscaCategoriaFerragemPropertyChange(evt);
            }
        });
        jIF_BuscaCategoriaFerragem.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTF_BuscarCategoriaFerragen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_BuscarCategoriaFerragen.setText("Buscar");
        jTF_BuscarCategoriaFerragen.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102,176,175)));
        jPanel27.add(jTF_BuscarCategoriaFerragen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 326, -1));

        jT_BucarCategoriaFerragem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jT_BucarCategoriaFerragem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_BucarCategoriaFerragemMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jT_BucarCategoriaFerragem);

        jPanel27.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 520, 330));

        jButton5.setText("Adcionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel27.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 80, -1));

        jButton6.setText("Buscar");
        jPanel27.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jIF_BuscaCategoriaFerragem.getContentPane().add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 420));

        jDesktopPane1.add(jIF_BuscaCategoriaFerragem, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 550, 460));

        JPanelPlanoFundo.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 520, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelPlanoFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelPlanoFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // <editor-fold defaultstate="collapsed" desc="Funções de atualização de tela"> 
    //função responsavel por mudar a tela ativa
    //pegando a tela que o usuario solicitou ela desativa todas mantendo so uma visivel
    private void activarJIF(JInternalFrame jInternalFrame){
        jIF_BuscarFerragens.setVisible(false);
        jIF_BuscarProjeto.setVisible(false);
        jIF_CadastroCliente.setVisible(false);
        jIF_CadastroFerragens.setVisible(false);
        jIF_CadastroProjeto.setVisible(false);
        jIF_CadastroProjeto2.setVisible(false);
        jIF_Home.setVisible(false);
        jIf_BuscarCliente.setVisible(false);
        jIF_CadastroCategoriaFerragens.setVisible(false);
        jInternalFrame.setVisible(true);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Atualizar JCombox"> 
    
    private void atualizarJcItensCadastrados(JComboBox jComboBox){
        CategoriaFerragenDAO categoriaFerragenDAO = new CategoriaFerragenDAO();
        List<CategoriaFerragens> categoriaFerragenses = categoriaFerragenDAO.listar();
        for (int i = 0; i < categoriaFerragenses.size(); i++) {
            jComboBox.addItem(categoriaFerragenses.get(i).getDescricao());
        }
    }
    
    private void atualizarJcProjetoCliente(){
        ClienteDAO clienteDAO = new ClienteDAO();
        List<Cliente> clientes = clienteDAO.listar();
        for (int i = 0; i < clientes.size(); i++) {
            jCB_ClienteProjeto.addItem(clientes.get(i).getNome());
        }
    }
    
    private void atualizarJcProjetoItens(CategoriaFerragens categoriaFerragens){
        FerragensDAO ferragensDAO = new FerragensDAO();
        List<Ferragens> ferragenses = ferragensDAO.listarCampos("categoriaFerragens", categoriaFerragens);
        for (int i = 0; i < ferragenses.size(); i++) {
            jCB_ProjetoFerragen.addItem(ferragenses.get(i).getDescricao());
            jCB_idFerragen.addItem(String.valueOf(ferragenses.get(i).getId()));
        }
    }
    
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Atualizar Tabela"> 
    //atualiza as informações da tela buscar cliente
    ClienteTabelModel clienteTabelModel;
    public void atualizarTabelaBuscarCliente(){
            ClienteDAO clienteDAO = new ClienteDAO();
            clienteTabelModel = new ClienteTabelModel(clienteDAO.listar());
            jT_BuscarCliente.setModel(clienteTabelModel);
    }
    CategoriaFerragensTableModel categoriaFerragensTableModel;
    public void atualizarTabelaBuscarCategoriaFerragen(){
            CategoriaFerragenDAO categoriaFerragenDAO = new CategoriaFerragenDAO();
            categoriaFerragensTableModel = new CategoriaFerragensTableModel(categoriaFerragenDAO.listar());
            jT_BucarCategoriaFerragem.setModel(categoriaFerragensTableModel);
    }
    FerragensTableModel ferragensTableModel;
    public void atualizarTabelaBuscarFerragen(){
            FerragensDAO ferragensDAO = new FerragensDAO();
            ferragensTableModel = new FerragensTableModel(ferragensDAO.listar());
            jT_BuscarFerragens.setModel(ferragensTableModel);
    }
    ProjetoTableModel projetoTableModel;
    public void atualizarTabelaBuscarProjeto(){
            ProjetoDAO projetoDAO = new ProjetoDAO();
            projetoTableModel = new ProjetoTableModel(projetoDAO.listar());
            jT_BuscarProjeto.setModel(projetoTableModel);
    }
    ProjetoFerragemTableModel projetoFerragemTableModel;
    public void atualizarTabelaProjetoFerragem(Projeto projeto){
            ProjetoFerragemDAO projetoFerragemDAO = new ProjetoFerragemDAO();
            projetoFerragemTableModel = new ProjetoFerragemTableModel(projetoFerragemDAO.listarCampos("projeto", projeto));
            jTb_ProjetoFerragen.setModel(projetoFerragemTableModel);
    }
    
    
    // </editor-fold>
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Eventos"> 
    private void jTF_NomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_NomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_NomeClienteActionPerformed

    private void jTF_TelefoneClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TelefoneClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TelefoneClienteActionPerformed

    private void jTF_CpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_CpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_CpfClienteActionPerformed

    private void jTF_EnderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_EnderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_EnderecoClienteActionPerformed

    private void jTF_BairroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_BairroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_BairroClienteActionPerformed

    private void jTF_CidadeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_CidadeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_CidadeClienteActionPerformed

    private void jTF_DescricaoFerragenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_DescricaoFerragenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_DescricaoFerragenActionPerformed

    private void jTF_ValorFerragenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_ValorFerragenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_ValorFerragenActionPerformed

    private void jTF_FormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_FormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_FormaPagamentoActionPerformed

    private void jTF_ComodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_ComodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_ComodoActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        activarJIF(jIf_BuscarCliente);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        activarJIF(jIF_BuscarProjeto);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        activarJIF(jIF_BuscarFerragens);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        activarJIF(jIF_CadastroFerragens);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        limparBuscaCliente();
        activarJIF(jIF_CadastroCliente);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
        activarJIF(jIF_CadastroProjeto);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        activarJIF(jIF_Home);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jL_CadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_CadastrarClienteMouseClicked
        try {
            //teste se existe algum campo vazio, testando tanto como campo vazio e com o texto padrao
            // caso algum campo esteja vazio o cliente não podera ser cadastrado
            if(jTF_NomeCliente.getText().equals("Nome Completo") || jTF_NomeCliente.getText().isEmpty() ||
               jTF_CpfCliente.getText().equals("Cpf") || jTF_CpfCliente.getText().isEmpty() ||
               jTF_TelefoneCliente.getText().equals("Telefone") || jTF_TelefoneCliente.getText().isEmpty() ||
               jTF_EnderecoCliente.getText().equals("Endereço") || jTF_EnderecoCliente.getText().isEmpty() ||
               jTF_BairroCliente.getText().equals("Bairro") || jTF_BairroCliente.getText().isEmpty() ||
               jTF_CidadeCliente.getText().equals("Cidade") || jTF_CidadeCliente.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Algum campo esta em branco");
            }else{
                cliente.setNome(jTF_NomeCliente.getText());
                cliente.setCpf(jTF_CpfCliente.getText());
                cliente.setTelefone(jTF_TelefoneCliente.getText());
                cliente.setEndereco(jTF_EnderecoCliente.getText());
                cliente.setBairro(jTF_BairroCliente.getText());
                cliente.setCidade(jTF_CidadeCliente.getText());
                cliente.setAtivo(true);
                cliente.setDataCadastro(new Date());
                
                ClienteDAO clienteDAO = new ClienteDAO();
                clienteDAO.salvar(cliente);
                limparCadastroCliente();
                if(jCB_ManterTela.isSelected()){
                    jL_MsgCadastroCliente.setText("Cliente " + cliente.getNome()+" salvo com sucesso");
                }else{
                    JOptionPane.showMessageDialog(null, "Cliente salvo com sucesso");
                    activarJIF(jIf_BuscarCliente);
                }
                jL_CadastrarCliente.setText("Cadastrar");
                jCB_ManterTela.setVisible(true);
                cliente = new Cliente();
            }
        } catch (Exception e) {
            System.out.println("Erro no cadastro do cliente: " + e);
        }
    }//GEN-LAST:event_jL_CadastrarClienteMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
         activarJIF(jIF_Home);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jL_CadastrarFerragemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_CadastrarFerragemMouseClicked
        //cadastro de ferragem
        try {
            //teste se existe campo vazio
            if(jTF_DescricaoFerragen.getText().equals("Descrição") || jTF_DescricaoFerragen.getText().isEmpty() ||
            jTF_ValorFerragen.getText().equals("Valor Compra") || jTF_ValorFerragen.getText().isEmpty() || 
            jCB_ItensFerragens.getSelectedIndex() < 0){
               JOptionPane.showMessageDialog(null, "Algum dos campos estão em branco");
            }else{
                CategoriaFerragenDAO categoriaFerragenDAO = new CategoriaFerragenDAO();
                //teste na conversao do valor para double
                try {
                    ferragens.setValor(Double.parseDouble(jTF_ValorFerragen.getText()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro no valor do produto");
                }
                ferragens.setDescricao(jTF_DescricaoFerragen.getText());
                ferragens.setCategoriaFerragens(categoriaFerragenDAO.listar().get(jCB_ItensFerragens.getSelectedIndex()));
                ferragens.setAtivo(true);
                ferragens.setDataCadastro(new Date());
                
                FerragensDAO ferragensDAO = new FerragensDAO();
                ferragensDAO.salvar(ferragens);
                
                if(jCB_ManterTelaCadastroFerragens.isSelected()){
                    jL_MsgCadastroFerragens.setText("Ferragen " + ferragens.getDescricao()+" salva com sucesso");
                }else{
                    JOptionPane.showMessageDialog(null, "Ferragem salva com sucesso");
                    activarJIF(jIF_BuscarFerragens);
                    jL_CadastrarFerragem.setText("");
                    jCB_ManterTelaCadastroFerragens.setSelected(false);
                }
                limparCadastroFerragem();
                jL_CadastrarFerragem.setText("Cadastrar");
                jCB_ManterTelaCadastroFerragens.setVisible(true);
                ferragens = new Ferragens();
            }
        } catch (Exception e) {
            System.out.println("Erro no cadastro da ferragen " + e);
        }
    }//GEN-LAST:event_jL_CadastrarFerragemMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        activarJIF(jIF_Home);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        if(jCB_ClienteProjeto.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(null, "Nenhum Cliente Selecionado");
        }else if(jTF_Comodo.getText().equals("Comodo") || jTF_Comodo.getText().isEmpty() ||
                jTF_NumeroMoveis.getText().equals("Numero de Moveis") || jTF_NumeroMoveis.getText().isEmpty() ||
                jTF_FormaPagamento.getText().equals("Forma de Pagamento") || jTF_FormaPagamento.getText().isEmpty()||
                jDP_DataInicial.getDate().equals("") || jDP_DataFinal.getDate().equals("")){
            JOptionPane.showMessageDialog(null, "Algum Campo em Branco");
        }else if(jDP_DataInicial.getDate().before(new Date()) || jDP_DataFinal.getDate().before(jDP_DataInicial.getDate())){
            JOptionPane.showMessageDialog(null, "Datas Incompativeis");
        }else{
            try {
                ClienteDAO clienteDAO = new ClienteDAO();
                projeto.setCliente(clienteDAO.listar().get(jCB_ClienteProjeto.getSelectedIndex()));
                projeto.setComodo(jTF_Comodo.getText());
                projeto.setNumeroMoveis(jTF_NumeroMoveis.getText());
                projeto.setFormaPagamento(jTF_FormaPagamento.getText());
                projeto.setDataInico(jDP_DataInicial.getDate());
                projeto.setDataFinal(jDP_DataFinal.getDate());
                projeto.setAtivo(true);
                projeto.setDataCadastro(new Date());
                
                ProjetoDAO projetoDAO = new ProjetoDAO();
                projetoDAO.salvar(projeto);
                
                activarJIF(jIF_CadastroProjeto2);
            } catch (Exception e) {
                System.out.println("Erro no cadastro de projeto part1 " + e);
            }
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ProjetoDAO projetoDAO = new ProjetoDAO();
        projeto.setValorProjeto();
        projetoDAO.salvar(projeto);
       activarJIF(jIF_Home);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTF_NumeroMoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_NumeroMoveisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_NumeroMoveisActionPerformed

    private void jTF_BuscarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_BuscarClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_BuscarClienteKeyPressed

    private void jIf_BuscarClienteInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jIf_BuscarClienteInternalFrameActivated
        atualizarTabelaBuscarCliente();
    }//GEN-LAST:event_jIf_BuscarClienteInternalFrameActivated

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        limparCadastroCliente();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jL_ExcluirClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_ExcluirClienteMouseClicked
        if(jL_CadastrarCliente.getText().equals("Editar")){
            if(JOptionPane.showConfirmDialog(null, "Deseja Excluir o Cliente") == 0){
                try {
                    ClienteDAO clienteDAO = new ClienteDAO();
                    clienteDAO.deletar(cliente);
                    JOptionPane.showMessageDialog(null, "Cliente Excluido com sucesso");
                    limparCadastroCliente();
                    activarJIF(jIf_BuscarCliente);
                } catch (Exception e) {
                    System.out.println("Erro delete cliente" + e);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Função desabilitada");
        }
        
    }//GEN-LAST:event_jL_ExcluirClienteMouseClicked

    private void jT_BuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_BuscarClienteMouseClicked
        if(evt.getClickCount() == 2){
           limparBuscaCliente();
           activarJIF(jIF_CadastroCliente);
           passarValores(clienteTabelModel.getValueAt(jT_BuscarCliente.getSelectedRow())); 
           jL_CadastrarCliente.setText("Editar");
           jCB_ManterTela.setVisible(false);
        }
    }//GEN-LAST:event_jT_BuscarClienteMouseClicked

    private void jL_CadastrarCategoriaFerragensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_CadastrarCategoriaFerragensMouseClicked
        //cadastro de categoria de ferragem
        try {
            //primeiro testa os campos vazios
            if(jTF_DescricaoCategoriaFerragem.getText().equals("Descrição") || jTF_DescricaoCategoriaFerragem.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Existem campos em branco");
            }else{
                //se n tiver seta os valores na variavel CategoriaFerragem
                categoriaFerragens.setDescricao(jTF_DescricaoCategoriaFerragem.getText());
                categoriaFerragens.setAtivo(true);
                categoriaFerragens.setDataCadastro(new Date());
                //cria o dao e salva no banco de daos
                CategoriaFerragenDAO categoriaFerragenDAO = new CategoriaFerragenDAO();
                categoriaFerragenDAO.salvar(categoriaFerragens);
                //reseta valores padroes da tela
                limparCadastroCategoriaFerragem();
                //se a caixa de selação estiver marcada ele n sai da tela mas exibe a mensagem na label
                if(jCB_ManterTelaCategoriaFerragen.isSelected()){
                    jL_MsgCategoriaFerragem.setText("Categoria " + categoriaFerragens.getDescricao()+" salvo com sucesso");
                }else{
                    atualizarTabelaBuscarCategoriaFerragen();
                    JOptionPane.showMessageDialog(null, "Categoria salvo com sucesso");
                    activarJIF(jIF_BuscaCategoriaFerragem);
                }
                
                jL_CadastrarCategoriaFerragens.setText("Cadastrar");
                jCB_ManterTela.setVisible(true);
                categoriaFerragens = new CategoriaFerragens();
            }
        } catch (Exception e) {
            System.out.println("Erro no cadastro de categoria ferragem " + e);
        }
        
    }//GEN-LAST:event_jL_CadastrarCategoriaFerragensMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jTF_DescricaoCategoriaFerragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_DescricaoCategoriaFerragemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_DescricaoCategoriaFerragemActionPerformed

    private void jL_ExcluirCategoriaFerragemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_ExcluirCategoriaFerragemMouseClicked
        if(jL_CadastrarCategoriaFerragens.getText().equals("Editar")){
            if(JOptionPane.showConfirmDialog(null, "Deseja Excluir a categoria de ferragen") == 0){
                try {
                    categoriaFerragens.setAtivo(false);
                    categoriaFerragens.setDataDesativacao(new Date());
                    CategoriaFerragenDAO categoriaFerragenDAO = new CategoriaFerragenDAO();
                    categoriaFerragenDAO.salvar(categoriaFerragens);
                    JOptionPane.showMessageDialog(null, "Categoria excluida com sucesso");
                    limparCadastroCategoriaFerragem();
                    atualizarTabelaBuscarCategoriaFerragen();
                    activarJIF(jIF_BuscaCategoriaFerragem);
                } catch (Exception e) {
                    System.out.println("Erro delete categoriaFerragen" + e);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Função desabilitada");
        }
    }//GEN-LAST:event_jL_ExcluirCategoriaFerragemMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        activarJIF(jIF_CadastroCategoriaFerragens);
        limparBuscaCategoriaFerragem();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      //  atualizarTabelaBuscarCategoriaFerragen();
        activarJIF(jIF_BuscaCategoriaFerragem);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jIF_BuscaCategoriaFerragemInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jIF_BuscaCategoriaFerragemInternalFrameActivated
        
    }//GEN-LAST:event_jIF_BuscaCategoriaFerragemInternalFrameActivated

    private void jIF_BuscaCategoriaFerragemInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jIF_BuscaCategoriaFerragemInternalFrameOpened
     
    }//GEN-LAST:event_jIF_BuscaCategoriaFerragemInternalFrameOpened

    private void jIF_BuscaCategoriaFerragemPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jIF_BuscaCategoriaFerragemPropertyChange
       
    }//GEN-LAST:event_jIF_BuscaCategoriaFerragemPropertyChange

    private void jT_BucarCategoriaFerragemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_BucarCategoriaFerragemMouseClicked
        //editar categoria
        if(evt.getClickCount() == 2){
           limparBuscaCategoriaFerragem();
           activarJIF(jIF_CadastroCategoriaFerragens);
           passarValoresEditarCategoriaFerragens(categoriaFerragensTableModel.getValueAt(jT_BucarCategoriaFerragem.getSelectedRow())); 
           jL_CadastrarCategoriaFerragens.setText("Editar");
           jCB_ManterTelaCategoriaFerragen.setVisible(false);
        }
    }//GEN-LAST:event_jT_BucarCategoriaFerragemMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        limparCadastroCategoriaFerragem();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jT_BuscarFerragensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_BuscarFerragensMouseClicked
        //editar ferragem
        if(evt.getClickCount() == 2){
           limparBuscaFerragem();
           activarJIF(jIF_CadastroFerragens);
           passarValoresEditarFerragens(ferragensTableModel.getValueAt(jT_BuscarFerragens.getSelectedRow())); 
           jL_CadastrarFerragem.setText("Editar");
           jCB_ManterTelaCadastroFerragens.setVisible(false);
        }
    }//GEN-LAST:event_jT_BuscarFerragensMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
       //limpar ferragem 
       limparCadastroFerragem();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        if(jL_CadastrarFerragem.getText().equals("Editar")){
            if(JOptionPane.showConfirmDialog(null, "Deseja Excluir a Ferragem") == 0){
                try {
                    ferragens.setAtivo(false);
                    ferragens.setDataDesativacao(new Date());
                    FerragensDAO ferragensDAO = new FerragensDAO();
                    ferragensDAO.salvar(ferragens);
                    JOptionPane.showMessageDialog(null, "Ferragem Excluido com sucesso");
                    limparCadastroFerragem();
                    atualizarTabelaBuscarFerragen();
                    activarJIF(jIF_BuscarFerragens);
                } catch (Exception e) {
                    System.out.println("Erro delete ferragem" + e);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Função desabilitada");
        }
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(jCB_ProjetoFerragen.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Nenhum Produto Selecionado");
        }else if(Integer.valueOf(jTF_Quantidade.getText()) <= 0){
            JOptionPane.showMessageDialog(null, "Quantidade Invalida");
        }else{
            try{
                projeto_ferragen projetoFerragem = new projeto_ferragen();
                projetoFerragem.setProjeto(projeto);
                FerragensDAO ferragensDAO = new FerragensDAO();
                Ferragens ferragens = ferragensDAO.listarCampos("id", Integer.valueOf(jCB_idFerragen.getItemAt(jCB_ProjetoFerragen.getSelectedIndex()))).get(0);
                projetoFerragem.setFerragens(ferragens);
                if(testeFerragemProjeto(projeto, ferragens) != null){
                    projetoFerragem = testeFerragemProjeto(projeto, ferragens);
                }  
                
                    
                projetoFerragem.setQuantidade(projetoFerragem.getQuantidade() + Integer.valueOf(jTF_Quantidade.getText()));
                projetoFerragem.setValorTotal(projetoFerragem.getValorTotal() + ferragens.getValor() * Integer.valueOf(jTF_Quantidade.getText()));
                projetoFerragem.setValorUnidade(ferragens.getValor());

                ProjetoFerragemDAO projetoFerragemDAO = new ProjetoFerragemDAO();
                projetoFerragemDAO.salvar(projetoFerragem);

               atualizarTabelaProjetoFerragem(projeto);
            
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jCB_ProjetoFerragenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_ProjetoFerragenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_ProjetoFerragenActionPerformed

    private void jCB_ProjetoCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCB_ProjetoCategoriaMouseClicked
        
    }//GEN-LAST:event_jCB_ProjetoCategoriaMouseClicked

    private void jCB_ProjetoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_ProjetoCategoriaActionPerformed
        if(iniciar){
            CategoriaFerragenDAO categoriaFerragenDAO = new CategoriaFerragenDAO();
            atualizarJcProjetoItens(categoriaFerragenDAO.listar().get(jCB_ProjetoCategoria.getSelectedIndex()));
        }
        
    }//GEN-LAST:event_jCB_ProjetoCategoriaActionPerformed
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Editar"> 
    
    //pega os valores do clinte selecionado e insere na tela para edição
    private void passarValores(Cliente cliente){
        this.cliente = cliente;
        jTF_NomeCliente.setText(cliente.getNome());
        jTF_CpfCliente.setText(cliente.getCpf());
        jTF_TelefoneCliente.setText(cliente.getTelefone()) ;
        jTF_EnderecoCliente.setText(cliente.getEndereco());
        jTF_BairroCliente.setText(cliente.getBairro());
        jTF_CidadeCliente.setText(cliente.getCidade());
        
    }
    private void passarValoresEditarCategoriaFerragens(CategoriaFerragens categoriaFerragens){
        this.categoriaFerragens = categoriaFerragens;
        jTF_DescricaoCategoriaFerragem.setText(categoriaFerragens.getDescricao()); 
    }
    private void passarValoresEditarFerragens(Ferragens ferragens){
        this.ferragens = ferragens;
        jTF_DescricaoFerragen.setText(ferragens.getDescricao()); 
        jTF_ValorFerragen.setText(String.valueOf(ferragens.getValor())); 
        
        CategoriaFerragenDAO categoriaFerragenDAO = new CategoriaFerragenDAO();
        List<CategoriaFerragens> categoriaFerragens = categoriaFerragenDAO.listar();
        for (int i = 0; i < categoriaFerragens.size(); i++) {
           
           if(categoriaFerragens.get(i).getId()==(ferragens.getCategoriaFerragens().getId())){
               jCB_ItensFerragens.setSelectedIndex(i); 
               break;
           }
        }
        
    }
    // </editor-fold>
    
    //teste para saber se ja existe uma determinada ferragem no projeto
    private projeto_ferragen testeFerragemProjeto(Projeto projeto, Ferragens ferragens){
        ProjetoFerragemDAO ferragemDAO = new ProjetoFerragemDAO();
        List<projeto_ferragen> lista = ferragemDAO.listarCampos2("projeto", projeto, "ferragens", ferragens);
        if(lista.size() > 0){
            // se existir algum ferragem relacionado o projeto retorna verdadeiro
            return lista.get(0);
        }
        // se  não existir algum ferragem relacionado o projeto retorna falso
        return null;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Limpeza de telas"> 
    
    // <editor-fold defaultstate="collapsed" desc="limpeza de telas de clientes"> 
    //reseta valores padrões da tela de cadastro de cliente
    private void limparCadastroCliente(){
        jTF_NomeCliente.setText("Nome Completo");
        jTF_CpfCliente.setText("Cpf");
        jTF_TelefoneCliente.setText("Telefone") ;
        jTF_EnderecoCliente.setText("Endereço");
        jTF_BairroCliente.setText("Bairro");
        jTF_CidadeCliente.setText("Cidade");
        jL_MsgCadastroCliente.setText("");
        jCB_ManterTela.setSelected(false);
    }
    //reseta valores padrões da tela de busca de cliente
    private void limparBuscaCliente(){
        jTF_BuscarCliente.setText("Buscar");
    }
    // </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Limpeza de telas categoria Ferragem"> 
    //reseta valores padrões da tela de cadastro de categoria ferragem
    private void limparCadastroCategoriaFerragem(){
        jTF_DescricaoCategoriaFerragem.setText("Descrição");
        jL_MsgCategoriaFerragem.setText("");
        jCB_ManterTelaCategoriaFerragen.setSelected(false);
    }
    
     //reseta valores padrões da tela de busca de categoria ferragem
    private void limparBuscaCategoriaFerragem(){
        jTF_BuscarCategoriaFerragen.setText("Buscar");
    }
    // </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Limpeza de telas Ferragem"> 
    //reseta valores padrões da tela de cadastro de categoria ferragem
    private void limparCadastroFerragem(){
        jCB_ItensFerragens.setSelectedIndex(0);
        jTF_DescricaoFerragen.setText("Descrição");
        jTF_ValorFerragen.setText("Valor Compra");
    }
    
     //reseta valores padrões da tela de busca de categoria ferragem
    private void limparBuscaFerragem(){
        jTF_BuscarCategoriaFerragen.setText("Buscar");
    }
    // </editor-fold> 
    // </editor-fold> 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelPlanoFundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jCB_ClienteProjeto;
    private javax.swing.JComboBox<String> jCB_ItensFerragens;
    private javax.swing.JCheckBox jCB_ManterTela;
    private javax.swing.JCheckBox jCB_ManterTelaCadastroFerragens;
    private javax.swing.JCheckBox jCB_ManterTelaCategoriaFerragen;
    private javax.swing.JComboBox<String> jCB_ProjetoCategoria;
    private javax.swing.JComboBox<String> jCB_ProjetoFerragen;
    private javax.swing.JComboBox<String> jCB_idFerragen;
    private org.jdesktop.swingx.JXDatePicker jDP_DataFinal;
    private org.jdesktop.swingx.JXDatePicker jDP_DataInicial;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jIF_BuscaCategoriaFerragem;
    private javax.swing.JInternalFrame jIF_BuscarFerragens;
    private javax.swing.JInternalFrame jIF_BuscarProjeto;
    private javax.swing.JInternalFrame jIF_CadastroCategoriaFerragens;
    private javax.swing.JInternalFrame jIF_CadastroCliente;
    private javax.swing.JInternalFrame jIF_CadastroFerragens;
    private javax.swing.JInternalFrame jIF_CadastroProjeto;
    private javax.swing.JInternalFrame jIF_CadastroProjeto2;
    private javax.swing.JInternalFrame jIF_Home;
    private javax.swing.JInternalFrame jIf_BuscarCliente;
    private javax.swing.JLabel jL_CadastrarCategoriaFerragens;
    private javax.swing.JLabel jL_CadastrarCliente;
    private javax.swing.JLabel jL_CadastrarFerragem;
    private javax.swing.JLabel jL_ExcluirCategoriaFerragem;
    private javax.swing.JLabel jL_ExcluirCliente;
    private javax.swing.JLabel jL_MsgCadastroCliente;
    private javax.swing.JLabel jL_MsgCadastroFerragens;
    private javax.swing.JLabel jL_MsgCategoriaFerragem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTF_BairroCliente;
    private javax.swing.JTextField jTF_BuscarCategoriaFerragen;
    private javax.swing.JTextField jTF_BuscarCliente;
    private javax.swing.JTextField jTF_CidadeCliente;
    private javax.swing.JTextField jTF_Comodo;
    private javax.swing.JTextField jTF_CpfCliente;
    private javax.swing.JTextField jTF_DescricaoCategoriaFerragem;
    private javax.swing.JTextField jTF_DescricaoFerragen;
    private javax.swing.JTextField jTF_EnderecoCliente;
    private javax.swing.JTextField jTF_FormaPagamento;
    private javax.swing.JTextField jTF_NomeCliente;
    private javax.swing.JTextField jTF_NumeroMoveis;
    private javax.swing.JTextField jTF_Quantidade;
    private javax.swing.JTextField jTF_TelefoneCliente;
    private javax.swing.JTextField jTF_ValorFerragen;
    private javax.swing.JTable jT_BucarCategoriaFerragem;
    private javax.swing.JTable jT_BuscarCliente;
    private javax.swing.JTable jT_BuscarFerragens;
    private javax.swing.JTable jT_BuscarProjeto;
    private javax.swing.JTable jTb_ProjetoFerragen;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
