/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Classe.Usuario;
import DAO.UsuarioDAO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Lab1
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Loguin
     */
    public Login() {
        initComponents();
    }
    
    private void loguin(){
        if(jTF_email.getText().equals("")  || new String(jPF_senha.getPassword()).isEmpty()){
            JOptionPane.showMessageDialog(null, "Existem algum campo em branco");
        }else{
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            List<Usuario> usuarios = usuarioDAO.listarCampos2("login", jTF_email.getText(), "senha", new String(jPF_senha.getPassword()));
            if(usuarios.size() >= 1){
                this.dispose();
                Home home = new Home();
                home.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Usuario ou senha invalidos");
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jP_loguin = new javax.swing.JPanel();
        jL_loguin = new javax.swing.JLabel();
        jP_sair = new javax.swing.JPanel();
        jL_sair = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTF_email = new javax.swing.JTextField();
        jPF_senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(191, 154, 83));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 176, 175));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SENHA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EMAIL");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jP_loguin.setBackground(new java.awt.Color(0, 102, 102));
        jP_loguin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_loguin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_loguinMouseMoved(evt);
            }
        });
        jP_loguin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_loguinMouseExited(evt);
            }
        });
        jP_loguin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_loguin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_loguin.setForeground(new java.awt.Color(255, 255, 255));
        jL_loguin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_loguin.setText("Login");
        jL_loguin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_loguinMouseMoved(evt);
            }
        });
        jL_loguin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_loguinMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_loguinMouseExited(evt);
            }
        });
        jP_loguin.add(jL_loguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -1, 100, 40));

        jPanel2.add(jP_loguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 100, 40));

        jP_sair.setBackground(new java.awt.Color(0, 102, 102));
        jP_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_sair.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_sair.setBackground(new java.awt.Color(0, 102, 102));
        jL_sair.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_sair.setForeground(new java.awt.Color(255, 255, 255));
        jL_sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_sair.setText("Sair");
        jL_sair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jL_sair.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_sairMouseMoved(evt);
            }
        });
        jL_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_sairMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_sairMouseExited(evt);
            }
        });
        jP_sair.add(jL_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jPanel2.add(jP_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 100, 40));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 120, 10));

        jTF_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_emailActionPerformed(evt);
            }
        });
        jTF_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_emailKeyPressed(evt);
            }
        });
        jPanel2.add(jTF_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 260, 30));

        jPF_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPF_senhaActionPerformed(evt);
            }
        });
        jPF_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPF_senhaKeyPressed(evt);
            }
        });
        jPanel2.add(jPF_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 260, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 0, 420, 500));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 240, 20));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 300, 20));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(851, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jL_loguinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_loguinMouseClicked
        loguin();
    }//GEN-LAST:event_jL_loguinMouseClicked

    private void jL_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_sairMouseClicked
        this.dispose();
    }//GEN-LAST:event_jL_sairMouseClicked

    private void jTF_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_emailActionPerformed

    private void jPF_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPF_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPF_senhaActionPerformed

    private void jP_loguinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_loguinMouseMoved
        
    }//GEN-LAST:event_jP_loguinMouseMoved

    private void jL_loguinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_loguinMouseMoved
       
    }//GEN-LAST:event_jL_loguinMouseMoved

    private void jL_loguinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_loguinMouseExited
        
    }//GEN-LAST:event_jL_loguinMouseExited

    private void jP_loguinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_loguinMouseExited
        
    }//GEN-LAST:event_jP_loguinMouseExited

    private void jL_sairMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_sairMouseMoved
        
    }//GEN-LAST:event_jL_sairMouseMoved

    private void jL_sairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_sairMouseExited
        
    }//GEN-LAST:event_jL_sairMouseExited

    private void jPF_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPF_senhaKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loguin();
        }
    }//GEN-LAST:event_jPF_senhaKeyPressed

    private void jTF_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_emailKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loguin();
        }
    }//GEN-LAST:event_jTF_emailKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_loguin;
    private javax.swing.JLabel jL_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPF_senha;
    private javax.swing.JPanel jP_loguin;
    private javax.swing.JPanel jP_sair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTF_email;
    // End of variables declaration//GEN-END:variables
}
